#:schema node_modules/wrangler/config-schema.json
name = "freesocks-control-plane"
main = "src/index.js"
compatibility_date = "2024-06-05"
compatibility_flags = ["nodejs_compat"]

routes = [
	{ pattern = "freesocks.org/get", zone_name = "freesocks.org" },
    { pattern = "freesocks.org/delete", zone_name = "freesocks.org" }
]

### Cloudflare KV namespace bindings
kv_namespaces = [
  { binding = "FREESOCKS_OUTLINE_API_ENDPOINTS", id = "ID_HERE" },
  { binding = "FREESOCKS_OUTLINE_ACCESS_KEYS", id = "ID_HERE" },
  { binding = "FREESOCKS_OUTLINE_ACCESS_KEYS_DELETION", id = "ID_HERE" },
  { binding = "FREESOCKS_PROM_API_ENDPOINTS", id = "ID_HERE" }
]

[vars]

### Environment variables for the GET Worker
#TURNSTILE_SECRET_KEY = "" # Cloudflare Turnstile secret key, manage with `wrangler secret` https://developers.cloudflare.com/workers/wrangler/commands/#secret
#TURNSTILE_SITE_KEY = "" # Cloudflare Turnstile site key, manage with `wrangler secret` https://developers.cloudflare.com/workers/wrangler/commands/#secret
VAR_EXPIRATION_DAYS = "90" # Set the expiration period in days
VAR_PREFIX_DISGUISE = "&prefix=<%16%03%01%00%C2%A8%01%01>" # Custom text to append after the access URL
VAR_WEIGHT_LATENCY = "0.8" # Weight for latency in the score calculation
VAR_WEIGHT_ACCESS_KEY_COUNT = "0.2" # Weight for access key count in the score calculation
VAR_API_ENDPOINT_TIMEOUT = "5000" # Timeout duration for API endpoint requests (in milliseconds)

### Environment variables for the DELETE Worker
#SECRET_AUTH_TOKEN = "" # Set a random auth token, manage with `wrangler secret` https://developers.cloudflare.com/workers/wrangler/commands/#secret
#VAR_CF_ACCESS_CLIENT_ID = "" # Cloudflare Access Service Token details, manage with `wrangler secret` https://developers.cloudflare.com/workers/wrangler/commands/#secret
#VAR_CF_ACCESS_CLIENT_SECRET = "" # Cloudflare Access Service Token details, manage with `wrangler secret` https://developers.cloudflare.com/workers/wrangler/commands/#secret
VAR_PROM_QUERY_TIME_RANGE = "90d" # delete keys that have not been used for X number of days