import type { TierUpsert } from './contracts/admin';

export const DEFAULT_TIERS: TierUpsert[] = [
  {
    slug: 'free',
    name: 'Free',
    description: 'Anonymous, Turnstile-gated access for users in censored regions',
    backend: 'remnawave',
    monthlyTrafficGb: 50,
    deviceLimit: 1,
    hwidLimit: 1,
    hwidEnabled: true,
    trafficStrategy: 'MONTH',
    remnawaveSquadUuid: null,
    isDefaultFree: true,
    isActive: true,
    priority: 0,
    expirationDaysAfterMembershipLapse: 0,
  },
  {
    slug: 'member',
    name: 'Member',
    description: 'Standard FreeSocks supporters - 3 devices, 500GB/month',
    backend: 'remnawave',
    monthlyTrafficGb: 500,
    deviceLimit: 3,
    hwidLimit: 3,
    hwidEnabled: true,
    trafficStrategy: 'MONTH',
    remnawaveSquadUuid: null,
    isDefaultFree: false,
    isActive: true,
    priority: 10,
    expirationDaysAfterMembershipLapse: 7,
  },
  {
    slug: 'patron',
    name: 'Patron',
    description: 'Premium tier - 5 devices, unlimited traffic',
    backend: 'remnawave',
    monthlyTrafficGb: 0,
    deviceLimit: 5,
    hwidLimit: 5,
    hwidEnabled: true,
    trafficStrategy: 'NO_RESET',
    remnawaveSquadUuid: null,
    isDefaultFree: false,
    isActive: true,
    priority: 20,
    expirationDaysAfterMembershipLapse: 7,
  },
];
