export const AUTH_TOKEN = SECRET_AUTH_TOKEN;
export const turnstileSecretKey = TURNSTILE_SECRET_KEY;
export const turnstileSiteKey = TURNSTILE_SITE_KEY;
export const API_ENDPOINTS_NAMESPACE = FREESOCKS_OUTLINE_API_ENDPOINTS;
export const ACCESS_KEYS_NAMESPACE = FREESOCKS_OUTLINE_ACCESS_KEYS;
export const PROM_API_ENDPOINTS_NAMESPACE = FREESOCKS_PROM_API_ENDPOINTS;
export const CF_ACCESS_CLIENT_ID = VAR_CF_ACCESS_CLIENT_ID;
export const CF_ACCESS_CLIENT_SECRET = VAR_CF_ACCESS_CLIENT_SECRET;

export const EXPIRATION_DAYS = VAR_EXPIRATION_DAYS;
export const PREFIX_DISGUISE = VAR_PREFIX_DISGUISE;
export const WEIGHT_LATENCY = VAR_WEIGHT_LATENCY;
export const WEIGHT_ACCESS_KEY_COUNT = VAR_WEIGHT_ACCESS_KEY_COUNT;
export const API_ENDPOINT_TIMEOUT = VAR_API_ENDPOINT_TIMEOUT;
export const PROM_QUERY_TIME_RANGE = VAR_PROM_QUERY_TIME_RANGE;

export const STATE_NAMESPACE = FREESOCKS_STATE_KV;
export const MAX_KEYS_PER_RUN = VAR_MAX_KEYS_PER_RUN;
export const MINIMUM_BYTES_THRESHOLD = VAR_MINIMUM_BYTES_THRESHOLD;
export const MAX_RETRIES = VAR_MAX_RETRIES;
export const RETRY_DELAY = VAR_RETRY_DELAY;