// Idempotent pre-`up` secret bootstrap for a fresh deploy. Fills every
// GENERATABLE secret so a fresh `docker compose -f docker-compose.stack.yml
// --env-file <target> up` needs no manual `openssl rand`. It NEVER overwrites a
// value that is already set — only replaces empty / CHANGE_ME placeholders — so
// it is safe to re-run on testing, beta, and prod.
//
//   target env  (container infra, read by compose; .env.beta by default —
//       override with `bun scripts/bootstrap-secrets.mjs .env.prod` or
//       FCP_ENV_FILE): INSTANCE_SECRET, POSTGRES_PASSWORD, CAP_ADMIN_KEY
//       (random) + the CDN-blinding PUBLIC pins VITE_FS_* (baked into the SPA
//       build)
//   .env.convex (Convex deployment env, applied by the deployer):
//       the CDN-blinding SECRET keys FS_*                   (private halves)
//
// The five core app secrets (SESSION_SIGNING_KEY, ADMIN_SESSION_SIGNING_KEY,
// ADMIN_BOOTSTRAP_SECRET, IP_HASH_SALT, ACCOUNT_ID_PEPPER) are auto-generated by
// the deployer itself (docker/deploy-entrypoint.sh, generate-once) and are NOT
// touched here. EXTERNAL credentials (Cap site key/secret, WebAuthn, billing
// rails) cannot be generated and must be filled by hand before `up`.
//
// Run from the repo root:  bun scripts/bootstrap-secrets.mjs
import { existsSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import path from 'node:path';
import { generateE2eeKeys } from './gen-e2ee-keys.mjs';

// Repo root. FCP_BOOTSTRAP_ROOT overrides it (used by the dry-run test); the
// crypto/example imports still resolve against this script's real location.
const HERE = path.dirname(new URL(import.meta.url).pathname);
const ROOT = process.env.FCP_BOOTSTRAP_ROOT ?? path.resolve(HERE, '..');
// Target infra env file: `.env.beta` by default; override for other
// deployments — positional arg (`bun scripts/bootstrap-secrets.mjs .env.prod`)
// or FCP_ENV_FILE. The matching `.example` falls back to `.env.beta.example`
// when no target-specific example exists (prod has no .env.prod.example).
const TARGET_ENV = process.env.FCP_ENV_FILE ?? process.argv[2] ?? '.env.beta';
const TARGET_EXAMPLE = existsSync(path.join(ROOT, `${TARGET_ENV}.example`))
  ? `${TARGET_ENV}.example`
  : '.env.beta.example';
const ENV_BETA = path.join(ROOT, TARGET_ENV);
const ENV_CONVEX = path.join(ROOT, '.env.convex');

const randHex = (n = 32) =>
  [...crypto.getRandomValues(new Uint8Array(n))]
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');

const isPlaceholder = (v) => v === undefined || v === '' || /CHANGE_ME/.test(v);

function ensureFromExample(file) {
  if (existsSync(file)) return;
  // Prefer the file's own example (.env.convex.example); the TARGET env file
  // falls back to .env.beta.example when it has none (.env.prod).
  const own = `${file}.example`;
  const example = existsSync(own) ? own : path.join(ROOT, TARGET_EXAMPLE);
  copyFileSync(example, file);
  console.log(`[bootstrap] created ${path.basename(file)} from ${path.basename(example)}`);
}

/** Parse a KEY=VALUE file into { lines, get(key) }; preserves comments + order. */
function readEnv(file) {
  const lines = (existsSync(file) ? readFileSync(file, 'utf8') : '').split('\n');
  const get = (key) => {
    for (const line of lines) {
      const m = /^([A-Z0-9_]+)=(.*)$/.exec(line);
      if (m && m[1] === key) return m[2].replace(/^"(.*)"$/, '$1');
    }
    return undefined;
  };
  return { lines, get };
}

/** Set KEY=value: rewrite the first live OR commented occurrence, else append. */
function setEnv(env, key, value) {
  const live = new RegExp(`^${key}=`);
  const commented = new RegExp(`^#\\s*${key}=`);
  for (let i = 0; i < env.lines.length; i++) {
    if (live.test(env.lines[i]) || commented.test(env.lines[i])) {
      env.lines[i] = `${key}=${value}`;
      return;
    }
  }
  env.lines.push(`${key}=${value}`);
}

ensureFromExample(ENV_BETA);
ensureFromExample(ENV_CONVEX);
const beta = readEnv(ENV_BETA);
const convex = readEnv(ENV_CONVEX);
let betaDirty = false;
let convexDirty = false;
const generated = [];

// 1) Infra randoms in .env.beta (the compose ${VAR:?} guards need them pre-`up`).
for (const [key, n] of [
  ['INSTANCE_SECRET', 32],
  ['POSTGRES_PASSWORD', 24],
  ['CAP_ADMIN_KEY', 24],
]) {
  if (isPlaceholder(beta.get(key))) {
    setEnv(beta, key, randHex(n));
    betaDirty = true;
    generated.push(key);
  }
}

// 2) CDN-blinding keys: generate the whole set ONCE (when the HPKE secret is a
//    placeholder), writing the private halves to .env.convex and the public pins
//    to .env.beta TOGETHER so they always match. Idempotent: a set secret means a
//    prior run wrote both → skip. We never re-derive one side from the other (the
//    ML-DSA public isn't derivable from its secret via the lib), so the pair is
//    only ever written as a unit.
const hpkeSet = !isPlaceholder(convex.get('FS_SERVER_HPKE_SK'));
const pinSet = !isPlaceholder(beta.get('VITE_FS_SERVER_HPKE_PK'));
if (!hpkeSet && !pinSet) {
  const k = await generateE2eeKeys();
  for (const key of ['FS_SERVER_HPKE_SK', 'FS_MANIFEST_SK', 'FS_MANIFEST_SK_PQ']) {
    setEnv(convex, key, k[key]);
  }
  for (const key of [
    'VITE_FS_SERVER_HPKE_PK',
    'VITE_FS_SERVER_HPKE_KID',
    'VITE_FS_E2EE_SUITE_ID',
    'VITE_FS_MANIFEST_PK',
    'VITE_FS_MANIFEST_PK_PQ',
  ]) {
    setEnv(beta, key, k[key]);
  }
  betaDirty = convexDirty = true;
  generated.push('CDN-blinding keypair (FS_* secrets + VITE_FS_* public pins)');
} else if (hpkeSet !== pinSet) {
  console.error(
    '[bootstrap] WARNING: the CDN-blinding secret (FS_SERVER_HPKE_SK in .env.convex) and the ' +
      'public pins (VITE_FS_* in .env.beta) are out of sync — one is set, the other is not. ' +
      'Leaving BOTH untouched (a half-written pair must never deploy). To regenerate: clear ' +
      'FS_SERVER_HPKE_SK and the VITE_FS_* pins in BOTH files, then re-run; or set them by hand ' +
      'from `bun scripts/gen-e2ee-keys.mjs`.',
  );
}

if (betaDirty) writeFileSync(ENV_BETA, beta.lines.join('\n'));
if (convexDirty) writeFileSync(ENV_CONVEX, convex.lines.join('\n'));

// Summary.
console.log(
  generated.length === 0
    ? '[bootstrap] nothing to do — every generatable secret is already set.'
    : `[bootstrap] generated: ${generated.join('; ')}.`,
);
const capKey = readEnv(ENV_BETA).get('CAP_ADMIN_KEY');
if (capKey && !isPlaceholder(capKey)) {
  console.log(`[bootstrap] CAP_ADMIN_KEY (log into the Cap dashboard with this): ${capKey}`);
}
console.log(
  '[bootstrap] next: fill the EXTERNAL creds that cannot be generated — CAP_SITE_KEY / ' +
    'CAP_SECRET (from the Cap dashboard), WEBAUTHN_RP_ID / WEBAUTHN_ORIGIN, and any billing ' +
    'rail keys — in .env.convex, then run the compose `up`.',
);
