/**
 * Regenerate the MessageKey union (`src/client/lib/i18n/message-keys.ts`) from
 * the base catalog `messages/en.json`. Run by `i18n:compile`, so `t()`'s
 * call-site key checking stays in sync as keys are added/removed in the JSON
 * (the Paraglide output is JS+JSDoc, so we keep the literal-union type here).
 */
import { readFileSync, writeFileSync } from 'node:fs';

// The inlang message-format plugin stores messages NESTED (it unflattens dotted
// ids on write), so flatten back to the dotted message ids Paraglide compiles +
// `t()` calls with. A leaf is a string (simple message) or an array (a
// plural/variant message); a plain object is a group to recurse into.
function flatten(obj: Record<string, unknown>, prefix = ''): string[] {
  const out: string[] = [];
  for (const [k, v] of Object.entries(obj)) {
    if (!prefix && k === '$schema') continue;
    const full = prefix ? `${prefix}.${k}` : k;
    if (v !== null && typeof v === 'object' && !Array.isArray(v)) {
      out.push(...flatten(v as Record<string, unknown>, full));
    } else {
      out.push(full);
    }
  }
  return out;
}

const en = JSON.parse(readFileSync('messages/en.json', 'utf8')) as Record<string, unknown>;
const keys = flatten(en).sort();
const union = keys.map((k) => `  | ${JSON.stringify(k)}`).join('\n');
writeFileSync(
  'src/client/lib/i18n/message-keys.ts',
  '// AUTO-GENERATED by scripts/i18n-keys.ts from messages/en.json — do not edit.\n' +
    `export type MessageKey =\n${union};\n`,
);
// eslint-disable-next-line no-console
console.log(`wrote src/client/lib/i18n/message-keys.ts (${keys.length} keys)`);
