/**
 * Regenerate the MessageKey union (`src/client/lib/i18n/message-keys.ts`) from
 * the base catalog `messages/en.json`. Run by `i18n:compile`, so `t()`'s
 * call-site key checking stays in sync as keys are added/removed in the JSON
 * (the Paraglide output is JS+JSDoc, so we keep the literal-union type here).
 */
import { readFileSync, writeFileSync } from 'node:fs';

const en = JSON.parse(readFileSync('messages/en.json', 'utf8')) as Record<string, unknown>;
const keys = Object.keys(en)
  .filter((k) => k !== '$schema')
  .sort();
const union = keys.map((k) => `  | ${JSON.stringify(k)}`).join('\n');
writeFileSync(
  'src/client/lib/i18n/message-keys.ts',
  '// AUTO-GENERATED by scripts/i18n-keys.ts from messages/en.json — do not edit.\n' +
    `export type MessageKey =\n${union};\n`,
);
// eslint-disable-next-line no-console
console.log(`wrote src/client/lib/i18n/message-keys.ts (${keys.length} keys)`);
